
# Get all targets supported by rustc: `rustc --print target-list | column`

[target.riscv32imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tsrc/arch/riscv/linker32.ld",
]

[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tsrc/arch/riscv/linker64.ld",
]
